prompt1 = input("Select an adjective: ")
prompt2 = input("Select an adjective: ")
prompt3 = input("Select a noun: ")
prompt4 = input("Select a different noun: ")
prompt5 = input("Select a plural noun: ")
prompt6 = input("Select a game: ")
prompt7 = input("Select a plural noun: ")
prompt8 = input("verb ending in 'ing': ")
prompt9 = input("verb ending in 'ing': ")
prompt10 = input("Select a plural noun: ")
prompt11 = input("verb ending in 'ing': ")
prompt12 = input("Select a noun: ")
prompt13 = input("Select a plant: ")
prompt14 = input("Select a part of the body: ")
prompt15 = input("Select a place: ")
prompt16 = input("verb ending in 'ing': ")
prompt17 = input("Select an adjective: ")
prompt18 = input("Select a number: ")
prompt19 = input("Select a plural noun: ")

print("A vacation is when you take a trip to some " + prompt1 + " place")
print("with your " + prompt2 + " family. Usually you go to some place")
print("that is near a/an " + prompt3 + " or up on a/an "+ prompt4 + ".")
print("A good vacation place is on where you can ride " + prompt5)
print("or play " + prompt6 + " or go hunting for " + prompt7 + ". I like")
print("to spend my time " + prompt8 + " or " + prompt9 + ".")
print("When my parents go on a vacation, they spend their time eating")
print("three " + prompt10 + " a day, and fathers play golf, and mothers")
print("sit around " + prompt11 + ". Last summer, my little brother")
print("fell in a/an " + prompt12 + " and got poison " + prompt13 + " all")
print("over his " + prompt14 + ". My family is going to go to (the)")
print(prompt15 + ", and I will practice " + prompt16 + ". Parents")
print("need vacations more than kids because parents are always very")
print(prompt17 + " and because they have to work " + prompt18)
print("hours every day all year making enough " + prompt19 + " to pay")
print("for the vacation.")

